name: ShellCheck

on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Shellcheck
      uses: actions/checkout@v3

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error 
        scandir: ./verifier.sh